version: '3.8'

services:
  db:
    container_name: database
    image: postgres:13
    restart: always
    env_file:
      - '.env'
    volumes:
      - ./database:/var/lib/postgresql/
    ports:
      - 5430:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db
    env_file:
      - '.env'
  tgbot:
    container_name: tg_bot
    restart: always
    command: python3 app.py
    build:
      context: ./
    env_file:
      - '.env'
